### ISSUE TITLE
How can I get Value as interface

### ISSUE THREAD

**Issue by vietanhduong** [zclconf/go-cty#119]
How can I get the value in Value struct as interface?

**Comment by apparentlymart** [comment]
Hi @vietanhduong,

The `interface{}` field inside `cty.Value` is an implementation detail and intentionally not exposed directly.

**Comment by vietanhduong** [comment]
Thank you for answer me. What I'm doing is create a function to convert a `cty.Value` to `interface{}`. It's work really well, but I'm considering have any way better than my way? Because it's using recursive, and I don't want it.

**Comment by apparentlymart** [comment]
Hi @vietanhduong,

All of the algorithms in cty that work with arbitrary values are recursive in some way, whether it be recursive through the `cty.Value` collection/structural type nesting, or through something else like reflection over Go structs.

It seems like an inherently recursive problem to me, so I have trouble imagining any algorithms that wouldn't have the same _effect_ as recursion, even if they are e.g. a flat loop that manages a stack itself rather than using the Go runtime's own stack. So I'm not sure what to suggest, unless there is some way you can constrain the problem, such as:
* Working only with the primitive types, which means you'll never need to do any recursion.
* Setting a reasonable maximum depth after which your algorithm will abort with an error, or perhaps summarize the deep nodes using special placeholder values.
* Make your function take a static `cty.Type` that the value is expected to conform to and then do recursion over that type rather than over the value. That way you can be sure that the maximum stack depth will be the maximum depth of that predefined type, not some arbitrary depth decided by whoever constructed the `cty.Value`. (That is roughly what [`gocty`](https://pkg.go.dev/github.com/zclconf/go-cty/cty/gocty) does, although it uses predefined Go structs via the `reflect` package as the basis for the recursion, rather than a `cty.Type` directly.)

**Comment by vietanhduong** [comment]
Thank you, @apparentlymart. Seem like my question is answered. This issue will be closed here.
