### ISSUE TITLE
Extend FormatDateFunc to support seconds since Unix Epoch

### ISSUE THREAD

**Issue by benjamb** [zclconf/go-cty#130]
It would be handy to be able to convert a provided date to a Unix timestamp. I'm using packer which wraps this function via its `timestamp()` function.

**Comment by apparentlymart** [comment]
Hi @benjamb! Thanks for this suggestion.

I intended the `formatdate` function to be primarily for producing the various machine-readable-but-also-human-readable date formats defined in different IETF RFCs and other specifications.

While I can certainly see that having access to a "unix timestamp" might be useful in some situations, to me that feels like a separate function from `formatdate` because it's producing a single hard-coded representation of a timestamp, which would be weird to combine with the other formatted parts that `formatdate` works with. Also, the natural return type of this operation would be a number rather than a string.

Given that, I'd suggest creating a new function to convert a per-conventions timestamp (RFC 3339) into a Unix timestamp, rather than adding it to `FormatDateFunc`.

I'm currently being quite reserved about adding new functions directly in the `stdlib` package of this repository, because the scope there has already become much larger than I had originally imagined thanks to HashiCorp contributing upstream various functions that were originally written for HashiCorp Terraform. Therefore I don't think I'd want to add such a function in this repository right now, but HashiCorp has [its own library of `cty` functions](https://github.com/hashicorp/go-cty-funcs) in addition to the ones maintained in here, and so perhaps they'd be willing to accept a unix timestamp conversion function into that library instead, which HashiCorp Packer could then include.

Thanks again!

**Comment by benjamb** [comment]
@apparentlymart Thanks for the thorough response!

I agree it doesn't actually make much sense to extend `formatdate` to support this, and that perhaps I should open an issue downstream instead.

With regards to the HashiCorp `cty` library, that very much looks unmaintained, so that route is likely a non-starter.

**Comment by apparentlymart** [comment]
Hi @benjamb,

The library I linked to was created by the Packer team specifically to hold the functions that Packer uses that I elected not to accept upstream in this library, so I expect inactivity there is more a consequence of the library currently being "done" as far as Packer is concerned, rather than because it's closed to future enhancements. With that said though, it'd probably be best to start with an issue in the Packer repository first to see if the Packer team has an appetite to support it, and then from there they can decide whether they'd rather have it live inside the Packer codebase or in the shared library.

**Comment by benjamb** [comment]
@apparentlymart Ah, that makes sense.

Yeah I've opened an issue in the packer repository for now, we'll see what happens.
