### ISSUE TITLE
cty/json: configure (non-)HTML-escaping serialization

### ISSUE THREAD

**Issue by johakoch** [zclconf/go-cty#156]
`marshal()` uses `json.Marshal()` which encodes using HTMLEscape:

> So that the JSON will be safe to embed inside HTML <script> tags, the string is encoded using HTMLEscape, which replaces "<", ">", "&", U+2028, and U+2029 are escaped to "\u003c","\u003e", "\u0026", "\u2028", and "\u2029". This replacement can be disabled when using an Encoder, by calling SetEscapeHTML(false).

This behaviour is good for HTML settings.

The documentation for `func (*Encoder) SetEscapeHTML` states

> In non-HTML settings where the escaping interferes with the readability of the output, SetEscapeHTML(false) disables this behavior.

We use cty in a non-HTML setting. So it would be nice to be able to configure whether HTML escaping is applied (using `json.Marshal()`) or not (e.g. using a custom Encoder with `SetEscapeHTML(false)`).

**Comment by apparentlymart** [comment]
Hi @johakoch! Thanks for sharing this feature request.

While I can see that this extra escaping is a cosmetic irritant, it's still a valid serialization of the input data and so I feel disinclined to cause potential churn by changing the default behavior, or to complicate the API by making it configurable.

Can you say more about why it matters for your use-case exactly how the JSON data is encoded, assuming that it always generates valid JSON? When I wrote this I did it on the assumption that JSON encoded `cty` objects are primarily for machine consumption and so human readability was not a priority. That is also why it always generates minified JSON, for example, with no option to configure that either.

**Comment by malud** [comment]
Hi @apparentlymart .
For [Couper](https://couper.io) we use hcl as our configuration language which also allows to compose some individual payloads via variables either as part of  a response or request `json_body`. This is enabled with converting the related payload to **cty** and vice versa (hcl evaluation). At this point the user does not expect a modification of its content which happens due to the json.Marshal default behaviour.

A simple example which has be solved in our [fork](https://github.com/avenga/go-cty/pull/1):

```hcl
# simple server endpoint which reflects the client json payload
server {
  endpoint "/json" {
      response {
        json_body = request.json_body
      }
  }
}
```

```sh
curl -X POST -H "Content-Type: application/json" -d '{ "prop": "<p>html</p>" }' http://localhost:8080/json

{"prop":"\u003cp\u003ehtml\u003c/p\u003e"}
```
An additional use-case would be the proxy case which connects a (legacy?) system which may also send unescaped data and we want to read/sniff into them for whatever reasons which may prevent us to pipe the body.

So it may solve just our use-case but we could think about a better integration of an possible opt out for html escaping if you give us a thump up ;)

**Comment by apparentlymart** [comment]
Hi @malud! Sorry for the long delay in responding. (It's been a year, I see :grimacing:)

While I do understand that your specific application would benefit from more customization, the JSON encoding of values here is primarily intended for later decoding by the same `cty/json` package rather than for interop with other systems, and so I prefer to keep it simple and not add lots of customization options.

This repository is MIT licensed and the `cty/json` package depends only on the exported API of the main `cty` package, so I would suggest that if you need this functionality you can copy the `cty/json` package into your own codebase and maintain your own fork with the behavior you want. You shouldn't need to fork anything other than the `cty/json` package, since your fork can still call directly into the other packages in this codebase.

Sorry again for taking a long time to respond, and I you'll understand my reasons for declining this request. Thanks!
