### ISSUE TITLE
adding jsonencode() block into a generated terraform file using golang cty 

### ISSUE THREAD

**Issue by gohayon-cls** [zclconf/go-cty#164]
Hi
Kind of new at this, so apology in advance if I'm asking a question that was answered already.
I'm trying to generate a tf file using the golang cty library.
It's pretty straightforward. However, I have this section:

```
  custom_fields = {
    alternate_contact = jsonencode({somecode})
}
```

How can I add the jsonencode() section into my generated tf file

**Comment by apparentlymart** [comment]
Hi @gohayon-cls,

It looks like your goal here is to generate Terraform language code using HCL syntax. This repository only deals with values in memory and knows nothing about the Terraform language in particular.

I think a good place for this question would be [Terraform's community forum](https://discuss.hashicorp.com/c/terraform-core/27), where I've seen questions similar to this one before. If you start a new topic there and share the code you already wrote as a starting point I expect someone can suggest how to change it to generate a function call.

Since this repository doesn't deal with Terraform language syntax, I'm going to close this issue. Thanks!

**Comment by gohayon-cls** [comment]
Perfect, thanks for taking the time to reply back to me.
