### ISSUE TITLE
`ObjectVal` or `MapVal `without `NormalizeString`

### ISSUE THREAD

**Issue by monegim** [zclconf/go-cty#184]
I wanted to convert a `map[string]Value` to the `cty.Value`, however, I do not want to normalize the attr. Is there any way to do this? 
As I checked the sourcecode the `ObjectVal` and `MapVal` normalize the attribute.

If it is not implemented could I create a PR for this feature?

**Comment by apparentlymart** [comment]
Hi @monegim,

It's an intentional design decision that all strings in `cty` -- which includes map keys and the attribute names of an object type -- are always stored in normalized form. This is one of the many invariants that comes from `cty`'s focus on standardization of representations and a focus on configuration-language-related use-cases. I don't wish to complicate things further by introducing the possibility that some values may not have been normalized, since that would then require robust calling applications to always handle both cases.

I'd be interested to learn more about your underlying goal though, in case I can propose an alternative way to achieve it without modifying `cty`. Thanks!

**Comment by monegim** [comment]
Hi @apparentlymart 

Thank you for getting back to me. I am trying to solve the [How to convert (write) hcl files as tfvars?](https://stackoverflow.com/questions/78717482/how-to-convert-write-hcl-files-as-tfvars) question.
This is a part of `tfvars` file I wanted to generate from a `hcl` file: 
```hcl
firewall = {
  "16abbc94-4048" = {
    action                = "allow"
    domain                = "example.com"
    filter_expr           = "((ip.src == 1.1.1.1))"
    is_enabled            = true
    name                  = "Simple"
  }
```
Reading a `hcl` file, converting to `cty.Value` and then printing as the `tfvars` file. The code for outputting this is as follows:

```go
func Hcl2CtyValue(hclFile *hcl.File, spec hcldec.Spec) cty.Value {
	value, diags := hcldec.Decode(hclFile.Body, spec, nil)
	if diags.HasErrors() {
		log.Fatal(diags.Error())
	}
	return value
}

func HCLWriter(obj cty.Value) []byte {
	f := hclwrite.NewEmptyFile()
	body := f.Body()
	for it := obj.ElementIterator(); it.Next(); {
		k, v := it.Element()
		name := k.AsString()
		// Purify
		// Iterate through Ids
		reconstructedValueMap := make(map[string]cty.Value, 0)
		for resources := v.ElementIterator(); resources.Next(); {
			id, resource := resources.Element()
			idString := id.AsString()
			reconstructedValueMap[fmt.Sprintf("%q", idString)] = resource
		}

		body.SetAttributeValue(name, cty.ObjectVal(reconstructedValueMap))
	}
	return f.Bytes()
}

```
but it would generate this:
```hcl
firewall = {
  "\"16abbc94-4048\"" = {
    action                = "allow"
    domain                = "example.com"
    filter_expr           = "((ip.src == 1.1.1.1))"
    is_enabled            = true
    name                  = "Simple"
  }
```
As you can see, normalizing would add `\"` to the key. I cannot access to the `cty.Value` I can remove the `NormalizeString` func. 
And this is the module for using the `tfvars` as a variable file:
```hcl
resource "firewall" "this" {
  for_each = {
    for k,v in var.firewall : k => v 
    if var.enable_firewall
  }
  domain      = each.value.domain
  name =        each.value.name
  filter_expr = each.value.filter_expr
  is_enabled  = each.value.is_enabled
  action =      each.value.action
}
```

**Comment by apparentlymart** [comment]
Hi @monegim,

In the code you shared you are constructing the key using `fmt.Sprintf("%q", idString)`, which I believe is what adds these extra quotes.

`cty` string normalization does not add quotes; it only ensures that the unicode characters in the given string are encoded in a predictable way so that rune-based string manipulation will always behave the same way for a given string.

I expect that if you change that line to the following then you will no longer produce these extra quotes:

```go
reconstructedValueMap[idString] = resource
```

**Comment by monegim** [comment]
Removing `fmt.Sprintf("%q", idString)` does not print `" "` at all. Something like this would be generated:

```hcl
firewall = {
# Note double quotes are not printed:
  16abbc94-4048 = {
    action                = "allow"
    domain                = "example.com"
    filter_expr           = "((ip.src == 1.1.1.1))"
    is_enabled            = true
    name                  = "Simple"
  }
```

**Comment by apparentlymart** [comment]
You are describing a formatting decision made by `hclwrite`, which is separate from any behavior in this repository. There's nothing you can do using the `cty` API to influence how `hclwrite` decides to render a value, because `cty` knows nothing about HCL.

It doesn't make any practical difference whether or not that attribute name is written in quotes. Terraform (really: HCL) understands it the same either way.

**Comment by monegim** [comment]
So you mean I could use an attribute without quotes?
But I get this error from terraform and that is why I tried to put the attr in the quotes:
```
Missing key/value separator: Expected an equals sign ("=") to mark the beginning of the attribute value. If you intended to given an attribute name containing periods or spaces, write the name in quotes to create a string literal.
```
