### ISSUE TITLE
Some method to avoid the lexicographical order when parsing tokens

### ISSUE THREAD

**Issue by glfdominguez** [zclconf/go-cty#186]
https://github.com/zclconf/go-cty/blob/9a4ed1eca4e031e6fc36475d3f3cfb861c7be2d6/cty/element_iterator.go#L60

There is a method to avoid this?, I'm trying to modify a .tfvars trying to change only what it's needed, nothing more... But this modifies a full map when is saved again.

**Comment by apparentlymart** [comment]
Hi @glfdominguez,

If the element iterator didn't sort the keys then the result would be in an unspecified order, and so that also wouldn't meet your goal of preserving the source order. Once data has been converted into a `cty` map value the original ordering has already been lost, because maps are an unordered data structure.

It sounds like you are trying to do something with HashiCorp's HCL to modify a file in Terraform's `.tfvars` format. The normal HCL API also doesn't preserve the order of attributes, but the special [`hclwrite`](https://pkg.go.dev/github.com/hashicorp/hcl/v2@v2.21.0/hclwrite) package does. I expect that you will need to use that package if you wish to perform surgical modifications to an existing HCL configuration file. `Body.SetAttributeValue` can surgically change the expression associated with an attribute, for example.

The third-party tool [`hcledit`](https://github.com/minamijoyo/hcledit) offers a higher-level way to use `hclwrite`'s functionality, which might be more convenient if your needs are relatively simple.

Performing surgical edits to HCL configuration files must be done using HCL itself rather than cty, so I'm going to close this issue. Thanks!
