### ISSUE TITLE
`Optional attribute modifier expects only one argument`

### ISSUE THREAD

**Issue by mclacore** [zclconf/go-cty#188]
Getting this error when trying to parse Terraform types that handle in-line defaults, such as:

```terraform
variable "withoptionaldefault" {
  type = object({
    foo = string
    fizz = optional(string, "fizz")
  })
  default = {"foo":"bar"}
}
```

Getting this error:

```
Error: :3,20-36: Invalid type specification; Optional attribute modifier expects only one argument: the attribute type.
```

**Comment by apparentlymart** [comment]
Hi @mclacore!

The error message you've described seems to originate from HashiCorp's downstream HCL library rather than from `cty`: https://github.com/hashicorp/hcl/blob/2442aca4bd4966af1429feb8698b43513d643a71/ext/typeexpr/get_type.go#L240-L246

However, based on my read of that code the decision for whether a default value is acceptable is made by HCL's caller rather than by HCL itself. From what you've described it sounds like you are the author of HCL's caller in this case, so my guess is that you're calling the HCL `typeexpr` extension in a different way than how Terraform calls it. Perhaps you are calling [`TypeConstraint`](https://pkg.go.dev/github.com/hashicorp/hcl/v2@v2.22.0/ext/typeexpr#TypeConstraint) instead of [`TypeConstraintWithDefaults`](https://pkg.go.dev/github.com/hashicorp/hcl/v2@v2.22.0/ext/typeexpr#TypeConstraintWithDefaults)?

There is no HCL expression evaluation/decoding logic in this repository, so I'm going to close this issue. If my guess above wasn't correct then I think you'll need to study the Terraform source code some more to make sure that your code uses the same evaluation rules as Terraform itself would use, but that's two levels downstream from `cty` so I can't help with that any further here. Thanks!
