### ISSUE TITLE
Incorrect $ parsing as string element

### ISSUE THREAD

**Issue by doctornkz** [zclconf/go-cty#24]
How repoduce:
Go to https://play.golang.org/
Put that code there:
```
package main
import (
	"fmt"
	"github.com/hashicorp/hcl2/hclwrite"
	"github.com/zclconf/go-cty/cty"
)
func main() {
	f := hclwrite.NewEmptyFile()
	rootBody := f.Body()
	rootBody.SetAttributeValue("hello", cty.StringVal("${world}"))
	fmt.Printf("%s", f.Bytes())
}
```
Receive:
```
hello = "$${world}"
```
Expected:
hello = "${world}"

I was trying a couple ways to escape that, but it doesn't work.

**Comment by doctornkz** [comment]
I found trick solution. If I use `cty.StringVal("${world}")` I am receiving `hello = "$$${world}"` and doubled `$$` compensate each other and it works like one `$`. But I think it's not good way to fix.

**Comment by apparentlymart** [comment]
Hi @doctornkz,

What you are seeing here seems to be an [HCL behavior](https://github.com/hashicorp/hcl2), not an HCL behavior. With that said, I believe it's working as intended because it's escaping the `${` sequence in your literal string so that the HCL parser would then see it as a literal `${` rather than the beginning of an interpolation sequence. If you'd like to discuss this more, please open an issue in the HCL repository.

**Comment by doctornkz** [comment]
I solved problem with hcl.Traversal() .Now, I can create templated config file. Ugly, but works good for me.

**Comment by marcsauter** [comment]
@doctornkz do you have an example of your solution?

**Comment by doctornkz** [comment]
@marcsauter take a look here: https://github.com/doctornkz/signalfx2terraform/blob/master/builder/dashboard.go#L79-L84 
it gives me possibility generate that example:
```
  chart {                  
    chart_id = "${signalfx_time_chart.sfx-XXXXXX.id}"
    column   = 0    
    row      = 1
    width    = 6
    height   = 1                                                      
  }
```
with `${}` inside the structure

**Comment by marcsauter** [comment]
Thank you so much, that solves out problem.
