### ISSUE TITLE
Possible bug: Vendor conflict

### ISSUE THREAD

**Issue by Ghost---Shadow** [zclconf/go-cty#26]
I am new to go, my understanding of this error message is that somewhere in my code it is registering from the `/vendor` and somewhere it is getting the absolute path. 

```sh
panic: gob: registering duplicate types for "github.com/zclconf/go-cty/cty.primitiveType": cty.primitiveType != cty.primitiveType

goroutine 1 [running]:
encoding/gob.RegisterName(0xc0001b4450, 0x2b, 0x3ff4e40, 0xc000422b93)
        /usr/local/Cellar/go/1.12.9/libexec/src/encoding/gob/type.go:820 +0x55e
github.com/terraform-providers/terraform-provider-alicloud/vendor/github.com/zclconf/go-cty/cty.init.3()
        /Users/souradeepnanda/go/src/github.com/terraform-providers/terraform-provider-alicloud/vendor/github.com/zclconf/go-cty/cty/types_to_register.go:52 +0x56a
```

Is there a way to not make it panic? 

Why is `cty.primitiveType != cty.primitiveType`?

**Comment by apparentlymart** [comment]
Hi @Ghost---Shadow,

It looks like your program is importing `cty` from two different locations... possibly once from the alicloud provider's vendor directory and once directly from your `GOPATH`.

This library expects to be included in the program only at one import path, because it registers itself with the `encoding/gob` package.

It looks like perhaps you are compiling the alicloud provider in "GOPATH mode", which is the mode from before Go Modules was introduced in Go 1.11 and is still the default for backward compatibility. You might get better results if you force Go to use the Go Modules mode by setting this environment variable:

```
GO111MODULE=on
```

The Terraform providers and this cty library are both Go Modules codebases, and so they may not build correctly in GOPATH mode.

**Comment by Ghost---Shadow** [comment]
Thanks
