### ISSUE TITLE
Should KeysFunc only return set(string) when given a map?

### ISSUE THREAD

**Issue by jbardin** [zclconf/go-cty#49]
Current `KeysFunc` returns either a `list(string)` or a tuple with the correct number of string values when given an object. Because of the key constraints of maps and objects, both of these can be converted to directly to `set(string)`. 

While in most cases cty consumers will automatically convert these as needed, conversion is still necessary. The question was brought about by using map keys as an argument to `for_each` through modules where authors would like to discourage the use of the object values.  See https://github.com/hashicorp/terraform/issues/24409

**Comment by jbardin** [comment]
Closing since the tuple return type has value, and the returning either a set or tuple will impact the validity of other derived expressions, I don't think we can change this at this time.

**Comment by apparentlymart** [comment]
I'm not sure I fully understood what you were saying here so maybe I'm just restating what you were saying already, but `keys` and `values` both return lists here so that the following can be an identity transform...

```hcl
f = zipmap(keys(a), values(a))
```

...and thus, it becomes possible to do other things that rely on being able to correlate the results of those functions.

While it doesn't necessarily _need_ to be possible to do the above, backward compatibility with that sort of usage is why they continued to return lists in the port to `cty` even though in principle `keys` could've changed to returning a set.
