### ISSUE TITLE
Coalesce function that now returns empty strings breaks lookup pattern

### ISSUE THREAD

**Issue by sigil66** [zclconf/go-cty#87]
With TF the following pattern can be used:

```hcl
${ coalesce(lookup(cloud.tags, "OrgXID", ""), lookup(cloud.tags, "org-xid", "")) }
```
Coalesce returning the empty string breaks the pattern.
Unfortunately lookup, does not accept null for the default argument which is required.

Is there another way to look for a value that may not exist, in a cty map? It seems like if the change to coalesce is desired then lookup should allow a default that is null.

**Comment by apparentlymart** [comment]
Hi @sigil66,

While Terraform is indeed using the `coalesce` function from this library, the situation you've described seems to be with a combination of features particular to Terraform. For that reason, it'll be up to the Terraform team to decide what their expected behavior is for this scenario, and if they want to propose a change to `cty` then they can open an issue or pull request to do so once they've completed their analysis.

For that reason, I'd ask you to report this as an issue in the Terraform repository first, and then let the Terraform team send a request upstream if the analysis of that issue suggests a change to this library. Thanks!
